#!/bin/bash
if [[ ! -z $1 ]]; then
    docker start $1
    docker exec -it $1 /bin/bash
else
    echo "Usage : dockerin <container_name>"
    echo "Available Docker Containers : "
    docker ps -a
fi
