#!/bin/bash
if [[ ! -z $1 ]]; then
    if [ "$1" = "distclean" ]
    then
        echo "Do you really want to delete all containers and images? [y/n]"
        read want
        if [ "$want" = "y" ]
        then
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -q)
        fi
    elif [ "$1" = "allcontainer" ]
    then
        docker rm $(docker ps -a -q)
    elif [ "$1" = "dangleimage" ]
    then
        docker rmi $(docker images -f "dangling=true" -q)
    elif [ "$1" = "container" ]
    then
        docker stop $2
        docker rm $2
    elif [ "$1" = "image" ]
    then
        docker rmi $2
    else
        echo "Not support operation"
    fi
else
    echo "Usage : dockerclean <distclean|dangleimage|allcontainer|image|container> [id|name]"
    echo "dockerclean distclean : stop/delete all containers, then delete all images"
    echo "dockerclean dangleimage : delete all none tag images"
    echo "dockerclean allcontainer : delete all containers (no stop)"
    echo "dockerclean image <id> : delete a image named <id>"
    echo "dockerclean containter <id> : delete a container named <id>"
fi
